name: Test Recommendations

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  recommend-tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history
      - name: Debug Git Info
        run: |
          git branch
          git remote -v
          git status
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Generate Mock Test Recommendations
        run: |
          node scripts/mock-recommend-tests.js
          echo "Content of test-recommendations.json:"
          cat test-recommendations.json
      - name: Add Recommendations as Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            try {
              const recommendations = JSON.parse(fs.readFileSync('test-recommendations.json', 'utf8'));
              console.log('Parsed recommendations:', recommendations);
              const checkboxes = recommendations.map(test => `- [ ] ${test}`).join('\n');
              const commentBody = `## Recommended Tests\n${checkboxes}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: context.issue.number,
                body: commentBody
              });
              console.log('Comment added successfully');
            } catch (error) {
              console.error('Error adding comment:', error);
              core.setFailed(`Action failed with error: ${error}`);
            }